version: '1'
services:
  database:
    image: postgres
    volumes:
      - ./data/pgdata:/pgdata
    env_file:
      - '.env'
  web:
    links:
      - database
    build: .
    volumes:
      - .:/opt/fooapp
    ports:
      - '3000:3000'
    command: [bundle, exec, puma]
    env_file:
      - '.env'